/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/assessments/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assessment.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assessments.index"];
        put?: never;
        post: operations["assessments.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/assessments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assessments.show"];
        put: operations["assessments.update"];
        post?: never;
        delete: operations["assessments.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.assessment.assessment.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.assessment.assessment.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["course.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["courses.index"];
        put?: never;
        post: operations["courses.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["courses.show"];
        put: operations["courses.update"];
        post?: never;
        delete: operations["courses.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.course.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.course.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/user
         *     نقطة التحقق الأساسية: "هل المستخدم مسجل دخول؟"
         */
        get: operations["auth.currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/grades/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["grade.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["grades.index"];
        put?: never;
        post: operations["grades.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/grades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["grades.show"];
        put: operations["grades.update"];
        post?: never;
        delete: operations["grades.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.grade.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.grade.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lesson.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lessons.index"];
        put?: never;
        post: operations["lessons.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lessons.show"];
        put: operations["lessons.update"];
        post?: never;
        delete: operations["lessons.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.lesson.lesson.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.lesson.lesson.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/login */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/logout */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/options/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["option.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["options.index"];
        put?: never;
        post: operations["options.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["options.show"];
        put: operations["options.update"];
        post?: never;
        delete: operations["options.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/paragraphs/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["paragraph.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/paragraphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["paragraphs.index"];
        put?: never;
        post: operations["paragraphs.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/paragraphs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["paragraphs.show"];
        put: operations["paragraphs.update"];
        post?: never;
        delete: operations["paragraphs.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paragraphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.lesson.paragraph.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paragraphs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.lesson.paragraph.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/forgot-password */
        post: operations["passwordReset.sendResetLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/reset-password */
        post: operations["passwordReset.reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["question.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["questions.index"];
        put?: never;
        post: operations["questions.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["questions.show"];
        put: operations["questions.update"];
        post?: never;
        delete: operations["questions.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/register */
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["semester.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["semesters.index"];
        put?: never;
        post: operations["semesters.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/semesters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["semesters.show"];
        put: operations["semesters.update"];
        post?: never;
        delete: operations["semesters.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.semester.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.semester.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stages/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stage.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stages.index"];
        put?: never;
        post: operations["stages.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stages.show"];
        put: operations["stages.update"];
        post?: never;
        delete: operations["stages.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.stage.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.stage.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subjects/next-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subject.nextOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subjects.index"];
        put?: never;
        post: operations["subjects.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subjects.show"];
        put: operations["subjects.update"];
        post?: never;
        delete: operations["subjects.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.subject.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["domains.curriculum.subject.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/uploads/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentRequest */
        AssessmentRequest: {
            lesson_id: number;
            paragraph_id?: number | null;
            /** @enum {string} */
            type: "pre" | "formative" | "final";
            title?: string | null;
            sort_order?: number;
        };
        /** AssessmentResource */
        AssessmentResource: {
            id: string;
            lesson_id: string;
            paragraph_id: string;
            type: string;
            title: string;
            sort_order: string;
            questions?: components["schemas"]["QuestionResource"][];
        };
        /** CourseRequest */
        CourseRequest: {
            subject_id: number;
            name: string;
            slug?: string | null;
            description?: string | null;
            image?: string | null;
            icon?: string | null;
            color?: string | null;
            sort_order?: number;
            is_published?: boolean;
        };
        /** CourseResource */
        CourseResource: {
            id: string;
            subject_id: string;
            name: string;
            slug: string;
            description: string;
            image: string;
            icon: string;
            color: string;
            sort_order: string;
            is_published: string;
            children?: components["schemas"]["LessonResource"][];
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** GradeRequest */
        GradeRequest: {
            stage_id: number;
            name: string;
            slug?: string | null;
            image?: string | null;
            icon?: string | null;
            color?: string | null;
            sort_order?: number;
            is_published?: boolean;
        };
        /** GradeResource */
        GradeResource: {
            id: string;
            stage_id: string;
            name: string;
            slug: string;
            image: string;
            icon: string;
            color: string;
            sort_order: string;
            is_published: string;
            children?: components["schemas"]["SubjectResource"][];
        };
        /** LessonRequest */
        LessonRequest: {
            course_id: number;
            title: string;
            slug?: string | null;
            summary?: string | null;
            image?: string | null;
            video?: string | null;
            icon?: string | null;
            color?: string | null;
            sort_order?: number;
            is_published?: boolean;
        };
        /** LessonResource */
        LessonResource: {
            id: string;
            course_id: string;
            title: string;
            slug: string;
            summary: string;
            image: string;
            video: string;
            video_embed: string | null;
            icon: string;
            color: string;
            sort_order: string;
            is_published: string;
            children?: components["schemas"]["ParagraphResource"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** OptionRequest */
        OptionRequest: {
            question_id: number;
            content: string;
            is_correct: boolean;
            sort_order?: number;
        };
        /** OptionResource */
        OptionResource: {
            id: string;
            question_id: string;
            content: string;
            sort_order: string;
            is_correct?: string;
        };
        /** ParagraphRequest */
        ParagraphRequest: {
            lesson_id: number;
            title: string;
            type?: string;
            slug?: string | null;
            image?: string | null;
            video?: string | null;
            icon?: string | null;
            color?: string | null;
            content: string;
            sort_order?: number;
        };
        /** ParagraphResource */
        ParagraphResource: {
            id: string;
            lesson_id: string;
            title: string;
            type: string;
            slug: string;
            image: string;
            video: string;
            video_embed: string | null;
            icon: string;
            color: string;
            content: string;
            sort_order: string;
        };
        /** QuestionRequest */
        QuestionRequest: {
            assessment_id: number;
            /** @enum {string} */
            type: "mcq" | "true_false";
            content: string;
            explanation?: string | null;
            correct_answer?: boolean | null;
            sort_order?: number;
        };
        /** QuestionResource */
        QuestionResource: {
            id: string;
            assessment_id: string;
            type: string;
            content: string;
            explanation: string;
            sort_order: string;
            correct_answer?: string;
            options?: components["schemas"]["OptionResource"][];
        };
        /** RegisterRequest */
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        /** SemesterRequest */
        SemesterRequest: {
            grade_id: number;
            name: string;
            sort_order?: number;
        };
        /** SemesterResource */
        SemesterResource: {
            id: string;
            grade_id: string;
            name: string;
            sort_order: string;
            children?: components["schemas"]["SubjectResource"][];
        };
        /** StageRequest */
        StageRequest: {
            name: string;
            slug?: string | null;
            image?: string | null;
            icon?: string | null;
            color?: string | null;
            sort_order?: number;
            is_published?: boolean;
        };
        /** StageResource */
        StageResource: {
            id: string;
            name: string;
            slug: string;
            image: string;
            icon: string;
            color: string;
            sort_order: string;
            is_published: string;
            children?: components["schemas"]["GradeResource"][];
        };
        /** SubjectRequest */
        SubjectRequest: {
            grade_id: number;
            semester_id?: number | null;
            name: string;
            slug?: string | null;
            image?: string | null;
            icon?: string | null;
            color?: string | null;
            sort_order?: number;
            is_published?: boolean;
        };
        /** SubjectResource */
        SubjectResource: {
            id: string;
            grade_id: string;
            semester_id: string;
            name: string;
            slug: string;
            image: string;
            icon: string;
            color: string;
            sort_order: string;
            is_published: string;
            children?: components["schemas"]["CourseResource"][];
        };
        /** UserResource */
        UserResource: {
            id: string;
            name: string;
            email: string;
            avatar: string;
            role: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "assessment.nextOrder": {
        parameters: {
            query?: {
                lesson_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "assessments.index": {
        parameters: {
            query?: {
                lesson_id?: number;
                paragraph_id?: number;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `AssessmentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssessmentResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "assessments.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssessmentResource"];
                        /** @constant */
                        message: "تم إنشاء التقييم بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "assessments.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AssessmentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssessmentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "assessments.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssessmentResource"];
                        /** @constant */
                        message: "تم تحديث التقييم بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "assessments.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف التقييم بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.assessment.assessment.index": {
        parameters: {
            query?: {
                lesson_id?: number;
                paragraph_id?: number;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `AssessmentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["AssessmentResource"] & Record<string, never>)[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.assessment.assessment.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AssessmentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssessmentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "course.nextOrder": {
        parameters: {
            query?: {
                subject_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "courses.index": {
        parameters: {
            query?: {
                subject_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `CourseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "courses.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseResource"];
                        /** @constant */
                        message: "تم إنشاء المقرر بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "courses.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CourseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "courses.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseResource"];
                        /** @constant */
                        message: "تم تحديث المقرر بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "courses.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف المقرر بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.course.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `CourseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.course.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CourseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.currentUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "grade.nextOrder": {
        parameters: {
            query?: {
                stage_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "grades.index": {
        parameters: {
            query?: {
                stage_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `GradeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GradeResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "grades.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GradeResource"];
                        /** @constant */
                        message: "تم إنشاء الصف بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "grades.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `GradeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GradeResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "grades.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GradeResource"];
                        /** @constant */
                        message: "تم تحديث الصف بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "grades.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف الصف بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.grade.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `GradeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["GradeResource"] & Record<string, never>)[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.grade.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `GradeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GradeResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lesson.nextOrder": {
        parameters: {
            query?: {
                course_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lessons.index": {
        parameters: {
            query?: {
                course_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `LessonResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lessons.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"];
                        /** @constant */
                        message: "تم إنشاء الدرس بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "lessons.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `LessonResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "lessons.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"];
                        /** @constant */
                        message: "تم تحديث الدرس بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "lessons.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف الدرس بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.lesson.lesson.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `LessonResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["LessonResource"] & Record<string, never>)[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.lesson.lesson.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `LessonResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم تسجيل الدخول بنجاح.";
                        user: components["schemas"]["UserResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم تسجيل الخروج بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "option.nextOrder": {
        parameters: {
            query?: {
                question_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "options.index": {
        parameters: {
            query?: {
                question_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `OptionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OptionResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "options.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OptionResource"];
                        /** @constant */
                        message: "تم إنشاء الخيار بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "options.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `OptionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OptionResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "options.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OptionResource"];
                        /** @constant */
                        message: "تم تحديث الخيار بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "options.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف الخيار بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "paragraph.nextOrder": {
        parameters: {
            query?: {
                lesson_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "paragraphs.index": {
        parameters: {
            query?: {
                lesson_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ParagraphResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ParagraphResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "paragraphs.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParagraphRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ParagraphResource"];
                        /** @constant */
                        message: "تم إنشاء الفقرة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "paragraphs.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ParagraphResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ParagraphResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "paragraphs.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParagraphRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ParagraphResource"];
                        /** @constant */
                        message: "تم تحديث الفقرة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "paragraphs.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف الفقرة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.lesson.paragraph.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ParagraphResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ParagraphResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.lesson.paragraph.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ParagraphResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ParagraphResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "passwordReset.sendResetLink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم إرسال رابط إعادة تعيين كلمة السر إلى بريدك الإلكتروني.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "passwordReset.reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم تغيير كلمة السر بنجاح، يمكنك تسجيل الدخول الآن.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "question.nextOrder": {
        parameters: {
            query?: {
                assessment_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "questions.index": {
        parameters: {
            query?: {
                assessment_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `QuestionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuestionResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "questions.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuestionResource"];
                        /** @constant */
                        message: "تم إنشاء السؤال بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "questions.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `QuestionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuestionResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "questions.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuestionResource"];
                        /** @constant */
                        message: "تم تحديث السؤال بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "questions.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف السؤال بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم إنشاء الحساب بنجاح.";
                        user: components["schemas"]["UserResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "semester.nextOrder": {
        parameters: {
            query?: {
                grade_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "semesters.index": {
        parameters: {
            query?: {
                grade_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SemesterResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SemesterResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "semesters.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemesterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SemesterResource"];
                        /** @constant */
                        message: "تم إنشاء الفصل الدراسي بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "semesters.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SemesterResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SemesterResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "semesters.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemesterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SemesterResource"];
                        /** @constant */
                        message: "تم تحديث الفصل الدراسي بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "semesters.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف الفصل الدراسي بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.semester.index": {
        parameters: {
            query?: {
                grade_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SemesterResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["SemesterResource"] & Record<string, never>)[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.semester.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SemesterResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SemesterResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "stage.nextOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "stages.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `StageResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StageResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "stages.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StageResource"];
                        /** @constant */
                        message: "تم إنشاء المرحلة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "stages.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `StageResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StageResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "stages.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StageResource"];
                        /** @constant */
                        message: "تم تحديث المرحلة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "stages.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف المرحلة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.stage.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `StageResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["StageResource"] & Record<string, never>)[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.stage.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `StageResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StageResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "subject.nextOrder": {
        parameters: {
            query?: {
                grade_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            next_order: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "subjects.index": {
        parameters: {
            query?: {
                grade_id?: number;
                semester_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SubjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubjectResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "subjects.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubjectResource"];
                        /** @constant */
                        message: "تم إنشاء المادة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "subjects.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SubjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubjectResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "subjects.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubjectResource"];
                        /** @constant */
                        message: "تم تحديث المادة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "subjects.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "تم حذف المادة بنجاح.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.subject.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SubjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["SubjectResource"] & Record<string, never>)[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "domains.curriculum.subject.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SubjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubjectResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "upload.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Maximum file size: 2048 kilobytes.
                     */
                    image: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            path: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
}
