import {
  Atom,
  BookCheck,
  BookCopy,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Brain,
  Calculator,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Cpu,
  FlaskConical,
  FunctionSquare,
  Globe,
  Globe2,
  GraduationCap,
  Landmark,
  Languages,
  LibraryBig,
  Medal,
  Microscope,
  NotebookPen,
  NotebookText,
  School,
  TestTube,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * حلّ الأيقونات المخزّنة كنص في قاعدة البيانات (أسماء lucide-react)
 * إلى مكوّنات SVG فعلية — بدل رسمها كنص مقصوص يتجاوز حاوية البطاقة.
 * أي اسم غير معروف يرجع null فيُستخدم رمز البديل في المكوّن.
 */
export const EXPLORE_ICONS: Record<string, LucideIcon> = {
  School,
  BookOpen,
  GraduationCap,
  BookMarked,
  Landmark,
  Languages,
  Calculator,
  Globe,
  Globe2,
  Wrench,
  Atom,
  FlaskConical,
  Cpu,
  FunctionSquare,
  TestTube,
  Microscope,
  Brain,
  NotebookPen,
  NotebookText,
  BookCopy,
  BookOpenCheck,
  LibraryBig,
  BookCheck,
  ClipboardList,
  ClipboardCheck,
  ClipboardPen,
  Medal,
};

